# -*- coding: utf-8 -*-
"""Copy of python day-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzltPpzfYE-44GmOMgXkgJzvGBbISdI0
"""

for i in range(1,11):
    for j in range(1,11):
        print("{:02d}".format(i*j),end=" ")
    print()

class Solution(object):
    def isperfectsquare(self,num: int)->bool:
        a=num**0.5
        if a%1==0:
            return True
        else:
            return False

a="i love india"
a.upper()
print(a)
print(a[::-1])

a="i love india"
a.upper()
c=a.swapcase()
print(c)

a="I Love India"
a.capitalize
print(a)

a="i love india"
e=a.find("love")
r=a.count("i")
print(e)
print(r)

a="i love india"
b=a.isupper()
c=a.isdigit()
d=a.isalpha()
print(b)
print(c)
print(d)

a="TVK is good and mass and cool"
b=a.split("and")
print(b)

a="vaishnavi is from mothkur and smart"
b=" ".join(a)
print(b)

a="VAISHNAVI IS FROM MOTHKUR and smart"
b=" ".join(i for i in a if i in "AEIOU")
print(b)

a=input("enter a password:")
up=0
sm=0
sp=0
dg=0
if len(a)>7:
  for i in a:
    if i.isupper():
      up=up+1
    elif i.islower():
      sm=sm+1
    else:
      sp=sp+1
  if up>0 and sp>0 and sm>0 and dg>0:
     print("strong")
  else:
    print("week")
else:
  print("week due to less char")

import time
import sys
h=3
m=40
s=0
while True:
  sys.stdout.write("\r{:02d}:{:02d}:{:02d}".format(h, m, s))
  sys.stdout.flush()
  time.sleep(1)
  s=s+1
  if s==60:
    m=m+1
    s=0
    if m==60:
      h=h+1
      m=0
      if h==24:
        h=0

from datetime import datetime
import pytz
a=pytz.timezone("Asia/Tokyo")
b=datetime.now(a)
print(b)
for i in pytz.all_timezones:
  print(i)